---
- name: Update web servers
  hosts: web

  tasks:
  - name: Ensure directory is created
    file:
      path: /home/centos/web
      state: directory

  - name: Ensure directory is created
    file:
      path: /home/centos/web2
      state: directory
...

