---
- name: Update web servers
  hosts: ubuntu
  become: yes

  tasks:
  - name: Update System
    apt:
      update_cache: yes

  - name: Ensure Apache Installed
    package:
      name: apache2
      state: present

  - name: Start Apache
    service:
      name: apache2
      state: started

  - name: Enable Apache
    service:
      name: apache2
      enabled: yes
...

