---
- name: Update web server
  hosts: web
  become: yes
  vars: 
    http_port: 9090

  tasks:

  - name: Update Config File
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf

  - name: Permissive Mode
    selinux:
      policy: targeted
      state: permissive

  - name: Restart Apache
    service:
      name: httpd
      state: restarted
...

