---
- name: Update Web servers
  hosts: all
  become: yes

  vars: 
    http_port: 9090

  handlers:
  - name: Restart Apache
    service:
      name: httpd
      state: restarted

  tasks:
  - name: Update System
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Ensure Apache Installed
    package:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Start Apache
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: Enable Apache
    service:
      name: apache2
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: Ensure Apache Installed
    package:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"

  - name: Start Apache
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: Enable Apache
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Update Config File
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - Restart Apache

  - name: Permissive Mode
    selinux:
      policy: targeted
      state: permissive

  - name: Update PHP App
    copy:
      src: date.php
      dest: /var/www/html/date.php

  - name: Install PHP 
    package:
      name: php
      state: present
    notify:
    - Restart Apache
...

